package com.github.nikita.zhdanov.favorite.recipes.controller;

import com.github.nikita.zhdanov.favorite.recipes.model.Recipe;
import com.github.nikita.zhdanov.favorite.recipes.service.RecipeService;
import io.swagger.annotations.ApiOperation;
import io.swagger.annotations.ApiParam;
import io.swagger.annotations.ApiResponse;
import io.swagger.annotations.ApiResponses;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import javax.validation.Valid;

@RestController
@RequestMapping("recipe")
public class RecipeController {
    @Autowired
    private RecipeService recipeService;

    @PutMapping(value = "/{id}")
    @ApiOperation("Add new or update existing recipe.")
    @ApiResponses({
            @ApiResponse(code = 200, message = "Recipe saved."),
            @ApiResponse(code = 500, message = "Internal server error."),
            @ApiResponse(code = 400, message = "Invalid request body provided.")
    })
    public ResponseEntity<?> put(
            @ApiParam(
                    value = "For new recipes should be generated by caller (UUID recommended). Max - 36 symbols.",
                    example = "12345678-1234-1234-1234-1234567890ab"
            ) @PathVariable("id") String id,
            @Valid @RequestBody Recipe recipe
    ) {
        recipe.setId(id);
        recipeService.save(recipe);
        return ResponseEntity.ok().build();
    }
}
